### ISSUE TITLE
How to generate Grad Cam Activation Map ?

### ISSUE THREAD

**Issue by jaskirat111** [haydengunraj/COVIDNet-CT#1]

**Comment by haydengunraj** [comment]
I'm not too familiar with Grad-Cam, but I believe you'll need to find the name of the final convolutional layer. There is some helpful discussion of Grad-Cam in the main COVID-Net repo: lindawangg/COVID-Net#64

**Comment by haydengunraj** [comment]
Note that we now provide code for Grad-CAM [here](https://github.com/haydengunraj/COVIDNet-CT/blob/master/inference_grad_cam.ipynb).
