### ISSUE TITLE
example code 

### ISSUE THREAD

**Issue by swankyshahir** [haydengunraj/COVIDNet-CT#10]
Thanks for building this much needed resource.

It would be mighty help if you could share the example code(may be a colab notebook) to read the pre-trained models and apply them on a CT-thorax. This way it could help healthcare workers like me ( a little technology challenged) apply your work for research purposes.

**Comment by haydengunraj** [comment]
That's a great idea! We do provide basic inference code in run_covidnet_ct.py, but I think you're right that a notebook would be easier to follow for those with less experience. I'll try to make a basic inference notebook to run the pretrained models and provide some visualizations.

**Comment by haydengunraj** [comment]
@swankyshahir , I added an inference notebook which also provides Grad-CAM visualizations. Hope this helps!

https://github.com/haydengunraj/COVIDNet-CT/blob/master/inference_grad_cam.ipynb
