### ISSUE TITLE
COVID-Net CT-2 

### ISSUE THREAD

**Issue by jomollin** [haydengunraj/COVIDNet-CT#11]
Hi,

i tied to run a prediction with COVID-Net CT-2.

I guess the run_covidnet_ct.py is changed as well. Will thy python run with the older models as well?

When I'm running it I always get an error:

python c:/covid-net/COVIDNet-CT-master/run_covidnet_ct_v2.py infer --model_dir C:/covid-net/COVIDNet-CT-master/COVID-Net-CT-2-L-(2A-RAD) --meta_name model.meta --ckpt_name model --image_file c:/test/d8e5991e-9c84-4b8e-887c-6522229c2570.jpg >c:/covid-net/values/pyresult1.2.840.113619.2.80.3826196142.24358.1611270218.2ct2l2ar.txt 

Traceback (most recent call last):
File \"c:/covid-net/COVIDNet-CT-master/run_covidnet_ct_v2.py\", line 402, in <module>
runner.infer(args.image_file, not args.no_crop)
AttributeError: 'Namespace' object has no attribute 'no_crop'
2021-01-28 18:06:04.390272: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll",

I hope you can help.

best regards
Joachim

**Comment by haydengunraj** [comment]
Hi Joachim,

The error you're getting seems to be a missing argument. Are you using the most recent version of utils.py?

**Comment by jomollin** [comment]
No, I didn't. That might be the problem. I will try immediately

**Comment by jomollin** [comment]
Thanks a lot, that solved the problem.

Anyway is the new python app capable od working with the Level 1 models?

**Comment by haydengunraj** [comment]
Yes, the previous models are compatible with the current code.
