### ISSUE TITLE
Mark images

### ISSUE THREAD

**Issue by jomollin** [haydengunraj/COVIDNet-CT#12]
Hi,

is there a way to get the information from the prediction to mark the found parts on our images (highlighted in red) like you have in your readme.md

Thanks
Joachim

Stay healthy!

**Comment by haydengunraj** [comment]
Hi Joachim,

The critical factors shown in the images are generated using GSInquire, which is a proprietary tool provided by DarwinAI Corp. Access to GSInquire may be granted to researchers or healthcare workers on a case-by-case basis, and the contact details to request access are provided in the README.

Alternatively, other users have had success using other visual explanation methods such as Grad-CAM, and if this is an avenue of interest I'd encourage you to check out the discussion in lindawangg/COVID-Net#64.

**Comment by haydengunraj** [comment]
@jomollin , I've added an inference notebook which provides Grad-CAM visualizations: https://github.com/haydengunraj/COVIDNet-CT/blob/master/inference_grad_cam.ipynb
