### ISSUE TITLE
Preprocessing DICOM to PNG

### ISSUE THREAD

**Issue by wjtan99** [haydengunraj/COVIDNet-CT#13]
Hi, Thanks a lot for sharing your data set and the code. 
I have a question. Your dataset images are in PNG format, I wonder if I have original DICOM files, what processing should I do to convert it to PNG file?  Do you have a code to share?

**Comment by haydengunraj** [comment]
The processing for DICOM depends on how the images are stored. Usually, the image data is stored in uint16 format and the DICOM header has two important tags: RescaleSlope and RescaleIntercept. To convert from the uint16 format to Housfield Units (HU), you would use the conversion:
`hu_data = uint16_data*RescaleSlope + RescaleIntercept`
This will yield signed HU values, which can then be converted to uint8 by applying a window. The `hu_to_uint8` function [here](https://github.com/haydengunraj/COVIDNet-CT/blob/6bf09df60292b75418f1613803d6b0bc2649ff5c/data_utils.py#L12) can perform this windowing for you (given a window width and window center), at which point the image can be saved as a PNG.

**Comment by wjtan99** [comment]
@haydengunraj Thanks for your reply. I noticed that in your dataset, a bounding box is provided. How do you get the bounding box? And in your classification network, do you crop the image in the bounding box?

**Comment by haydengunraj** [comment]
Bounding boxes for the patients' bodies were generated automatically using the [`auto_body_crop`](https://github.com/haydengunraj/COVIDNet-CT/blob/261207c6cb82a7cd11de7f70c0bb09b3f8d62505/data_utils.py#L44) function in `data_utils.py`. We crop the images using the bounding boxes during both training and testing, and for inference on new images the `auto_body_crop` function should be used.
