### ISSUE TITLE
Hyperparameter-tuning

### ISSUE THREAD

**Issue by maravind707** [haydengunraj/COVIDNet-CT#14]
Hi
I am interested to try out Hyperparameter-tuning
From all the examples of few packages like keras-tuner, tensor-board hyperparameter tunning, ray-tune, etc,
model architecture is coded using keras or tf, and they passing hyperparameters to that function.

Here, the network is loaded from the .meta file,
Q1: Is there a way to way to perform Hyperparameter-tuning here, any code available?
Q2: If not, Can you point me to any good package to do it and some reference links on how to do it.

Thanks

**Comment by haydengunraj** [comment]
Q1: We do not provide code for hyperparameter tuning in this repo.
Q2: This is also a no unfortunately, as I have limited experience with hyperparameter tuning in TensorFlow and I'm not sure which packages/reference materials would be appropriate.
