### ISSUE TITLE
Window set for prediction

### ISSUE THREAD

**Issue by jomollin** [haydengunraj/COVIDNet-CT#15]
Hallo,

which window setting (window width and window center) are you using for training? which shall I set for prediction (-500 1400)?

Which file format is better for prediction? JPG or PNG

Thanks in advance
Joachim

**Comment by jomollin** [comment]
Hi,
with the recommended window -500/1400 I get predictions with up to 600%. The recommendation came from a radiologist partner. Whats your recommendation. I didn't found yet

**Comment by haydengunraj** [comment]
Hi Joachim,

We recommend a -600/1500 window, as this is what was used for training and testing. -500/1400 should also work fine, as we tried to make these models reasonably robust to different window settings.

JPG and PNG are both appropriate for use with our models, especially if you have data which is already in one of these formats. However, if you're converting images from Hounsfield units to uint8, PNG would be your best bet to avoid unnecessary data loss.

**Comment by jomollin** [comment]
Hi,
thanks for your answers. But how could it be to get results >100%. One even with 630%

Any idea?

best Joachim

**Comment by haydengunraj** [comment]
Hmm, that's very strange. Are you able to provide some additional information about what you're running and what data you're using, or ideally a minimal working example?

**Comment by haydengunraj** [comment]
Closing now due to inactivity. Feel free to reopen if necessary.
