### ISSUE TITLE
Are the results per image only? 

### ISSUE THREAD

**Issue by wjtan99** [haydengunraj/COVIDNet-CT#17]
Hi, Thanks for sharing your great work. In the paper and this repo, I only see per image precision, sensitivity etc. Do you have results or how do you make decision for patient?

**Comment by haydengunraj** [comment]
Hi @wjtan99 ,

You are correct; in this work we focused on 2D detection, and so we don't have patient-level results to share at this time. If this is something you might be interested in, we've considered a few ways that volume-level predictions could be performed:

1. Use the provided models (or your own) to perform 2D inference on every slice in a CT volume, then predict COVID-19 if _any_ slice is predicted to be COVID-19-positive. There is an example [here](https://github.com/haydengunraj/COVIDNet-CT/blob/master/inference_grad_cam.ipynb) on how to run inference for a full CT volume. We haven't tried this approach at this point, but there is a potential problem: if some slices are predicted to be COVID-19-positive and others are predicted to be pneumonia-positive, you'd have to decide which prediction to choose.
2. Use one of the provided models as a feature extractor and add some sort of pooling operation (i.e., average, max, etc.) to combine the features extracted from the CT slices. This approach has been used in some 3D detection models (for example, [this one](https://pubs.rsna.org/doi/full/10.1148/radiol.2020200905) or [this one](https://pubs.rsna.org/doi/full/10.1148/radiol.2020201491)) and seems to be an effective approach.
3. Create a hybrid 2D/3D model using one of the provided models and a 3D detection head. This might look something like: (1) resample CT volumes to a fixed number of slices, (2) pass the fixed-size volumes through the 2D feature extractor, treating the volume's slice dimension as the batch dimension, (3) pass the resulting features through a small 3D network to perform the final prediction.

Approach 1 is the easiest, but is more of an approximation and is likely prone to errors. Approaches 2 and 3 would probably work better, but would require fine-tuning on a 3D dataset, which we have not provided here.

**Comment by wjtan99** [comment]
Thanks a lot for your suggestions. I already tried 1 and it did not work well.  I will try both 2 and 3.

**Comment by haydengunraj** [comment]
That's good to know, thanks!.
