### ISSUE TITLE
details workflow?

### ISSUE THREAD

**Issue by fm385bnx** [haydengunraj/COVIDNet-CT#20]
could you please share the step by step file execution process so that the whole model can be implemented without any error?

**Comment by haydengunraj** [comment]
Hi Faiza,

You'll need to be a bit more specific about which parts are unclear/not working. Assuming you have the necessary packages installed and the models/data downloaded, example commands for training/evaluating/testing the models are available [in the docs](https://github.com/haydengunraj/COVIDNet-CT/blob/master/docs/train_eval_inference.md).
