### ISSUE TITLE
missing images

### ISSUE THREAD

**Issue by mhmdsab** [haydengunraj/COVIDNet-CT#9]
are there missing images with the data, 'None type has no attribute ndims' error is thrown for many images

**Comment by AlexTS1980** [comment]
> are there missing images with the data, 'None type has no attribute ndims' error is thrown for many images

did you use the clean training split?

**Comment by mhmdsab** [comment]
I followed the default settings and around 700 were not found. I hope  there is a good description on how to reproduce the clean version of the data

**Comment by AlexTS1980** [comment]
> I followed the default settings and around 700 were not found. I hope there is a good description on how to reproduce the clean version of the data

If you refer to their train split, you should also have a look at the quarantine list. I sampled 3000 images randomly, didn't have any issues

**Comment by mhmdsab** [comment]
I guess u mean this file train_COVIDx-CT.txt, yes I know we should refer to this file, I just wanted to test the pretrained checkpoints.
By the way, the split files are referred by default in the utils.py file.

>   I sampled 3000 images randomly, didn't have any issues
3000 is just 3% of the data so u might escape finding missing image

**Comment by AlexTS1980** [comment]
> I guess u mean this file train_COVIDx-CT.txt, yes I know we should refer to this file, I just wanted to test the pretrained checkpoints.
> By the way, the split files are referred by default in the utils.py file.
> 
> > I sampled 3000 images randomly, didn't have any issues
> 
> 3000 is just 3% of the data so u might escape finding missing image

no I mean exclude_list.txt

**Comment by haydengunraj** [comment]
@mhmdsab I'll double-check the dataset preparation script when I get a chance - it worked correctly last time I checked, but the source data may have been modified since then. We're planning to release the dataset directly to make it easier to use (no need to download raw data and use the preparation scripts), so stay tuned for that.

**Comment by mhmdsab** [comment]
@AlexTS1980 the exclude_list.txt is added by default

**Comment by mhmdsab** [comment]
@haydengunraj I appreciate ur help. the data might has been changed little bit. I tested all images in test_COVIDx-CT.txt except 15 missing images. the accuracies are not the same as yours. sensitivity for covid19 class was 0.92 while yours was ~0.97.
I do not know why it is that different. is this related to autocrop=False argument. I made inference using inference function, not test function.
I hope u reply asap

**Comment by AlexTS1980** [comment]
> @haydengunraj I appreciate ur help. the data might has been changed little bit. I tested all images in test_COVIDx-CT.txt except 15 missing images. the accuracies are not the same as yours. sensitivity for covid19 class was 0.92 while yours was ~0.97.
> I do not know why it is that different. is this related to autocrop=False argument. I made inference using inference function, not test function.
> I hope u reply asap

The model is very small, and hence 1) it depends on a large training data with plenty of augmentation/balancing tricks, 2) it is sensitive to even small perturbations in the inputs. Try using something staple for comparison, like ResNet18/34/50, and train on a subset of the train split without any augmentations. Your results should be comparable or better+more stable. It's very straightforward to implement.

**Comment by mhmdsab** [comment]
@AlexTS1980 it doesn't depend on the model for results to be different. I followed the same code without any change. it should give same results.

**Comment by AlexTS1980** [comment]
> @AlexTS1980 it doesn't depend on the model for results to be different. I followed the same code without any change. it should give same results.

That's not what I meant at all. The achieved sensitivity (92% or similar) is very high for such a small model (2.5M parameters) and is due to various data tricks (see the dataset interface code). The model is also sensitive to the input, and maybe the difference is explained by the `autocrop=False`. A larger model shouldn't suffer from such small perturbations.

**Comment by mhmdsab** [comment]
UPDATE:
changing auto_crop argument in infer method to True gave me identical results

**Comment by haydengunraj** [comment]
@mhmdsab perfect, thanks for the update. I should have asked about that first since it's an important step - we crop images to the patient's body to try to standardize the field of view.

**Comment by haydengunraj** [comment]
@mhmdsab the cleaned data is now available on Kaggle: https://www.kaggle.com/hgunraj/covidxct
